### PR TITLE
API-breaking change: don't early-import models and signals.

### PR DESCRIPTION
**Pull request by akx**
This is required for Django 1.8+ compatibility.

### CODE REVIEW

**Comment by akx** [comment]
> So - does this mean that for third-party apps you should no longer import anything in your top level `__init__.py`?

You shouldn't import models in the module that Django imports when discovering apps, that's how I've understood it.

Client code will need to be changed to import from `.signals` and `.models` respectively, but that's the only change really. :)

**Comment by sklirg** [comment]
Shouldn't the tests be ran with Django 1.8 (or even 1.9)?

Please update tox.ini to test using a higher version of Django. (All testenvs currently use less than Django 1.8) - These errors happen during initialization of the project, errors should happen during initialization of the test suite as well.

**Comment by g-as** [comment]
Any updates on this guys?

**Comment by sklirg** [comment]
I'm using this PR in production. Haven't found any edge case bugs as of yet.

**Comment by akx** [comment]
This was apparently implemented in #21, so closing.

**Pull request closed without merging**
