### PR TITLE
Add django 1.9 support

### PR DESCRIPTION
**Pull request by sinitsynsv**

### CODE REVIEW

**Comment by g-as** [comment]
!

**Comment by MJafarMashhadi** [comment]
Why isn't this pull request merged? Is there any problems with it?

**Comment by alexislg2** [comment]
Can you merge it please?

**Comment by MJafarMashhadi** [comment]
@alexislg2 It seems this won't be merged soon, i recommend you to download and use the source code from @sinitsynsv account directly or use it as a git sub module

**Comment by glynjackson** [comment]
@MJafarMashhadi Is there a reason or something we can help with in regards to this not being merged?

**Comment by MJafarMashhadi** [comment]
@glynjackson I guess not. I used this in production without any problems.

**Comment by mauricioabreu** [comment]
👍

**Comment by sinitsynsv** [comment]
It seems that I broke tox configuration. Should I return coverage environment in tox.ini?

**Comment by mdamien** [comment]
[I repaired it](ece9b9a5e22b72e145a0125427603fcb2cf99913) (adding back the coverage tox env), I just need to put back the flake8 warnings too if I want to get back to the same state.

**Pull request merged**
