### PR TITLE
Retrofit

### PR DESCRIPTION
**Pull request by djedi**
If adding this package to a project that already has users in it, add emails to the email list and generate a confirmation key.

### CODE REVIEW

**Comment by djedi** [comment]
Any change I can get this merged and updated on PyPI?

**Comment by mfogel** [comment]
Hi @djedi, I appreciate the pull request. But I'm not nuts about changing the behavior of a 'get' method such that it'll alter state - ie. create an address object if one doesn't exist. If I were to change the behavior of the method like your pull request does, I'd also change the name of the method to 'get_or_create_...'. However, I'm not nuts about methods that do just that - may or may not change state when you call them. I prefer that the public methods presented by a class are very clear on what they do - so I'd rather they either 'get' or they 'create' - but not one of those sometimes and not others.

**Comment by djedi** [comment]
So how would you go about supporting an app that already has user data in it?

**Comment by mfogel** [comment]
If you install the app, including using `SimpleEmailConfirmationUserMixin` in your User model, then all of your existing Users should show up as unconfirmed. That is `User.is_confirmed` will be False.

If that's not what you'd like (ie you want your existing Users to show up as 'confirmed') then I would do a datamigration with South to add `EmailAddress` objects for each of your existing Users. If `EmailAddress.confirmed_at` is set to a datetime in the past, then the corresponding `User.is_confirmed` will return True.

**Comment by djedi** [comment]
Actually you get an EmailAddress.DoesNotExist error (at least for a custom user model), which is why I handled the exception like I did.

**Comment by mauricioabreu** [comment]
Does it still apply?

**Comment by mfogel** [comment]
I've cherry-picked and merged in the two commits adding functionality to the admin interface.

I'm not merging in the other commit for the reasons explained in the comments above. Open to other options, please open an issue or another pull request if you'd like to discus it further.

**Pull request closed without merging**
