### PR TITLE
Compatibility with Django >= 4.0

### PR DESCRIPTION
**Pull request by feroda**

### CODE REVIEW

**Comment by alpden550** [comment]
Please submit, it is very needful PR 😀

**Review by edmenendez — APPROVED** [review]

**Comment by kennell** [comment]
Can we get this merged please @mfogel ?

**Comment by mfogel** [comment]
Yes, I'll go ahead and merge, looks safe from reading the django 4.0 release notes. I don't use this app anymore so please let me know if this breaks anything.

**Comment by kennell** [comment]
@mfogel Thank you for merging this. Can you please also make a new release to PyPI?

**Comment by wghozayel** [comment]
@mfogel It would be awesome if you could please make a new release to PyPI with the Django 4+ compatible version :pray:

**Pull request merged**
