### PR TITLE
Fix for Django 2.0

### PR DESCRIPTION
**Pull request by wlonk**
Just involved adding a value for `on_delete`.

Here's a cute animal picture for you:

bison

### CODE REVIEW

**Comment by mdamien** [comment]
Very cute ! Tests are failing for an unrelated reason (python3.5 not found) but I'm gonna fix that, thanks for the PR !

**Comment by wlonk** [comment]
Thanks. I tested it locally with 3.5.2 and it worked, for what it's worth.

**Comment by mdamien** [comment]
I also detected via your PR that the lib installed Django 2.0 even if the python version is 2.7 (which crash of course)

This is gonna happen in a lot of unpinned libraries deps, details in cb79aae

**Comment by wlonk** [comment]
Ach, good catch, thank you.

**Pull request merged**
