### PR TITLE
Allow EmailAddress model override

### LINKED ISSUE #50: Specify custom EmailAddress model
It would be nice to be able to override the default EmailAddress model. In my case, I would like to use UUID PKs instead of the default AutoField.

Others might want to attach additional fields to the model.

### PR DESCRIPTION
**Pull request by ferndot**
Fix #50.

Please note that this is not backwards compatible (the import of the user mixin needed to change to avoid circular imports).

### CODE REVIEW

**Comment by jakeharding** [comment]
I'm just curious...Django uses a Meta class property called swappable to implement the custom user model, and this feature seems similar. Have you considered using swappable?

**Comment by ferndot** [comment]
@jakeharding thanks for mentioning that. I had actually never stumbled on that attribute. I am not sure if it would be wise to use it since it is not mentioned in the django docs and created mostly for use by the custom user model.

What do you all think?

**Comment by jakeharding** [comment]
Food for thought...I implemented this with swappable in my fork and it seemed to work fine for my use case. That doesn't mean it works for all use cases, and I didn't run any tests against it because I saw the issue and didn't know if someone had picked it up already. [Here's the diff based off develop of this repo](https://github.com/mfogel/django-simple-email-confirmation/compare/develop...jakeharding:feature/abstract_email?expand=1). @joshua-s I'm in no way trying to step on your toes, and I have no problem trying to prove this out using swappable if you think it will be worth it.

**Comment by ferndot** [comment]
@jakeharding thanks for linking that. I definitely think `swappable` is a more elegant solution with backwards compatibility and possibly fewer bugs. If nobody is concerned about its reliability, I vote we go with your solution.

**Comment by jakeharding** [comment]
@joshua-s, thanks for considering it. I will work up a PR but it may be this weekend before I can get to it.

**Comment by ferndot** [comment]
Closing in favor of #52

**Pull request closed without merging**
