### PR TITLE
Django3 compability

### LINKED ISSUE #67: Package breaks in Django >=3.0.0
Tested with `django==3.0.0` and `django==3.0.1`

```
File "/home/k/.virtualenvs/project/lib/python3.6/site-packages/simple_email_confirmation/models.py", line 9, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'

```

It seems that this was dropped in Django 3.0.0 (see [release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/)) and can simply be fixed by importing directly from `six`

### PR DESCRIPTION
**Pull request by kennell**
Fixes https://github.com/mfogel/django-simple-email-confirmation/issues/67

### CODE REVIEW

**Comment by kennell** [comment]
Seems like some of the existing tests are unstable, don't have time to investigate further ‾\_(ツ)_/‾

**Comment by kennell** [comment]
@mfogel Any chance on gettings this merged and released on PyPI?

**Comment by mdamien** [comment]
Sorry to be late, this looks perfect to me, for the tests, they are flaky and you passed 2/3 so it's ok

EDIT: released as 0.7

**Comment by kennell** [comment]
@mfogel or @mdamien Thanks for getting this merged. Can you please push v0.7 to PyPI? Thank you.

**Comment by mdamien** [comment]
It's already pushed :)

**Comment by kennell** [comment]
@mdamien I see you released it as `0.7` but there is a version `0.60` on PyPI. If you run a `pip install django-simple-email-confirmation` it will still install the `0.60` version because in SemVer `0.60` is > `0.7`

**Comment by mdamien** [comment]
Oops, my bad, uploading 0.70 then

EDIT: uploaded :)

**Comment by kennell** [comment]
Thanks

**Pull request merged**
